### ISSUE TITLE
Error with Delegation Identity

### ISSUE THREAD

**Issue by Nikola1994** [AstroxNetwork/agent_dart#7]
Hello,

When I try to use IC identity (using local page), I got a normal identity, and the result is like in the example project in this lib. After that, I am calling the IC canister, and I got an error.
Error:
`Unhandled Exception: Unhandled error Server returned an error: Code: 403 (Forbidden)`

`Body: Failed to authenticate request 0x5f5b53a270e40c4558549975f54c17163b24b337054255bc1c2e56705fab9860 due to: Invalid delegation: Invalid canister signature: IcCanisterSignature signature could not be verified: public key 0a000000000000000701012ad6fa197bcc32c16f588d58ccb0468c9bd039c9b60302ad08e03cda98f6243f, signature d9d9f7a26b63657a9.......678301820458200e729de08c6bfa677847fb8d7bcc79efc892045aed2c4b350f7c7446085257f5830182045820b71837514f52507ff04caee7b05a920f1d5ac8863b9d65d3489951ff33b1187e83025820f487586c5bdaaa19d6f10abc3626e44af4624a386c64832659da432f265a61f5830258208b8ee0cf244a56d1b8fa863141be1b473f9e0576d941282124d41e2b44793519820340, error: the signature tree doesn't contain sig/f487586c5bdaaa19d6f10abc3626e44af4624a386c64832659da432f265a61f5/2baf862838777c8dfc951a5b4b3768b5ce23bc641ea0a1172f3e0726de7ae936`

I don't have any problem with normal identity (created by myself), but this Delegation one made this error.

Do you have some idea how to solve this problem?

**Comment by neeboo** [comment]
Hi. Latest version should fix the problem. please update and see if the problem exist.

**Comment by Nikola1994** [comment]
Hi, thanks for your response.
I am using the latest version of the agent, and I put `debug: false`, but the error still exists.

**Comment by neeboo** [comment]
> Hi, thanks for your response.
> I am using the latest version of the agent, and I put `debug: false`, but the error still exists.

Would you like to share your pieces of code here, then I can debug. And what type of IC canister and what is the goal of calling it. Because the actor may use different identity before calling.

**Comment by Nikola1994** [comment]
Hello @neeboo,

Today, I started from your example project to put a minimum part of code that can test this issue. I push the code to this repo: https://github.com/Nikola1994/test-ic-agent

I moved Agent creation after login to Ic, so Agent will use Delegation Identity instead of Anonymous one. 
I still get the same error.

Thanks

**Comment by neeboo** [comment]
> Hello @neeboo,
> 
> Today, I started from your example project to put a minimum part of code that can test this issue. I push the code to this repo: https://github.com/Nikola1994/test-ic-agent
> 
> I moved Agent creation after login to Ic, so Agent will use Delegation Identity instead of Anonymous one.
> I still get the same error.
> 
> Thanks

Ok. Let me look into it and see if anything goes wrong

**Comment by neeboo** [comment]
Ok, I think i figure out something but not entirely confirmed, perhaps i just put it here and see if we can find out the truth.

1. Known bugs in `agent-dart` during the process,  the `Uint8Buffer` are widely used in cborDecode function, especially when it deocdes Map like JsonObject in json, they are shallowed that we don't know exactly the type. I just fix them during the process. But I don't think the bugs are the actual causes.

2. The Webauthn of II, the reason why I use the popup window to load the local page( `http://localhost.me:32768` ), because it's the only way to pop a authorize window of II, which only supports authing with web application( website of `ic0.app` especially). So the problem is that, the backend of II uses `domain name` of frontend to calculate the seed, and generate the delegated identity and principal ID. Now it causes 2 related problem. 1) different domain name get different output, which is the `http://localhost.me:32768` url is joined the calculation. 2) plus, the final delegated identity is combine-signature of our localhost page, not the real ic-canister you are targeting to.

3.  I'm not sure what is your signup method in the backend, but I think you surely use `caller` to get the current delegation identity. But as mentioned above, the identity is not for the ic-canister, it's for the localhost page, which will get the wrong signature, because your actor created is not yet delegated with the identity got from II.  To work around, you can see my branch :https://github.com/neeboo/test-ic-agent/tree/neeboo/fix , in https://github.com/neeboo/test-ic-agent/blob/9bb8661d1f5985d2bfe481bfb76ff3b791cb7130/lib/signup.dart#L89, you can use the delegation method to re-create the actor and do it to your application.

Anyway, I got the result by changing the `username` of your signup payload, now, the result may not be the best outcome, however the error is gone.

```bash
flutter: Start
flutter: {id: 35912569659080704, title: Title, username: usernametest2, link: www.google.com, cover: {canister_id: 2vxsx-fae, image_id: , timestamp: 0, format: }, education: Education, description: Description ..., display_name: Display name, company: company, image: {canister_id: 2vxsx-fae, image_id: , timestamp: 0, format: }, location: location}
flutter: End

``` 

4. The discussion is not done, because we know the problem 2 and 3, they won't get the solid result we expect. We hope to get Principal and DelegatedIdentity from II, just like a OAuth token or User ID somehow. And especially used for a mobile app like we build with flutter. Somehow II still not support that. So what I'm thinking that if you would like to experiment more, like create a auth page just like the `http://localhost.me:32768` and host it on your `ic0` website, and try to get the authorization again without the re-creation of actor and identity.   If that fails too, perhaps we should look for another way like our team is making alternative version of Identity service for wider developers and apps.

If you can give me some feed back and experimentation, it would be much appreciated!

**Comment by neeboo** [comment]
@Nikola1994 if you have solved the problem, you can close this one, thank you

**Comment by Nikola1994** [comment]
Yes, thanks for solving this issue.
